### ISSUE TITLE
about ICV_GetData.ipynb

### ISSUE THREAD

**Issue by LXYTSOS** [LucaMD/SRL#1]
Could you tell me where to download the MetaVision VUmc Database?

**Comment by LucaMD** [comment]
Hi LXTSOS, 

Please see this paper for the https://doi.org/10.1016/j.artmed.2020.102003 description of the ICV dataset. This dataset is now available in a anonymous form at http://b2find.eudat.eu/dataset/308a0c36-efc7-5277-aeb6-d32c406fae63 with documentation at https://github.com/AmsterdamUMC/AmsterdamUMCdb.

Due to the fact that the data has been anonymised the ICV data (used in this project) can not be made available to the public anymore, just to researchers in the field of intensive care. If you specifically need this dataset, please contact Paul Elbers @ https://amsterdammedicaldatascience.nl/.
