### ISSUE TITLE
Could you provide the processed ICV data?

### ISSUE THREAD

**Issue by LXYTSOS** [LucaMD/SRL#2]
Could you provide the processed ICV data?  because the original data is too large to download.

**Comment by LucaMD** [comment]
Hi LXTSOS, 

Please see this paper for the https://doi.org/10.1016/j.artmed.2020.102003 description of the ICV dataset. This dataset is now available in a anonymous form at http://b2find.eudat.eu/dataset/308a0c36-efc7-5277-aeb6-d32c406fae63 with documentation at https://github.com/AmsterdamUMC/AmsterdamUMCdb.

Due to the fact that the data has been anonymised the ICV data (used in this project) can not be made available to the public anymore, just to researchers in the field of intensive care. If you specifically need this dataset, please contact Paul Elbers @ https://amsterdammedicaldatascience.nl/.

To evaluate the model the data used for modelling, specifically the final_data_dict.pk (see https://github.com/LucaMD/SRL/blob/master/SEPSIS/experiments/FINAL/data/FINAL_data_dict.pkl) is available within this repository.
